import uuid
import csv
import io
from datetime import datetime
from database import get_db

class RewardSettings:
    @staticmethod
    def get_settings():
        """Retrieve active algorithm weights and profit pool settings."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM reward_settings ORDER BY id DESC LIMIT 1")
        settings = cursor.fetchone()
        conn.close()
        return settings

    @staticmethod
    def update_settings(visit_weight, spending_weight, referral_weight, profit_sharing_pool):
        """Update algorithm weights and profit pool settings."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO reward_settings (visit_weight, spending_weight, referral_weight, profit_sharing_pool)
            VALUES (?, ?, ?, ?)
        ''', (visit_weight, spending_weight, referral_weight, profit_sharing_pool))
        conn.commit()
        conn.close()


class EngagementEngine:
    @staticmethod
    def calculate_engagement_score(member_id):
        """
        Calculate a member's total engagement score based on configurable factors:
        - Member direct visits
        - Member direct spending
        - Guest referrals count
        - Guest spending attached to member
        """
        settings = RewardSettings.get_settings()
        v_weight = settings['visit_weight']
        s_weight = settings['spending_weight']
        r_weight = settings['referral_weight']

        conn = get_db()
        cursor = conn.cursor()

        # Count total member visits
        cursor.execute("SELECT COUNT(*) FROM activities WHERE member_id = ? AND activity_type = 'visit'", (member_id,))
        visit_count = cursor.fetchone()[0]

        # Calculate member direct spending
        cursor.execute("SELECT COALESCE(SUM(transaction_value), 0.0) FROM activities WHERE member_id = ? AND activity_type = 'purchase'", (member_id,))
        direct_spending = cursor.fetchone()[0]

        # Calculate total guest referrals count
        cursor.execute("SELECT COALESCE(SUM(guest_count), 0) FROM activities WHERE member_id = ? AND activity_type = 'referral'", (member_id,))
        direct_referrals = cursor.fetchone()[0]

        # Calculate guest spending generated by this member's guests
        cursor.execute('''
            SELECT COALESCE(SUM(ga.transaction_value), 0.0)
            FROM guest_activities ga
            JOIN guest_ids g ON ga.guest_id = g.id
            WHERE g.host_member_id = ?
        ''', (member_id,))
        guest_spending = cursor.fetchone()[0]

        conn.close()

        total_spending = direct_spending + guest_spending
        score = (visit_count * v_weight) + (total_spending * s_weight) + (direct_referrals * r_weight)
        
        return {
            'visit_count': visit_count,
            'direct_spending': direct_spending,
            'guest_spending': guest_spending,
            'total_spending': total_spending,
            'guest_referrals': direct_referrals,
            'engagement_score': round(score, 2)
        }

    @staticmethod
    def calculate_discount_band(score):
        """Map engagement score to personalized discount percentage band."""
        if score >= 350:
            return 20.0
        elif score >= 200:
            return 15.0
        elif score >= 100:
            return 10.0
        elif score >= 50:
            return 5.0
        return 0.0

    @classmethod
    def update_member_rewards(cls, member_id):
        """Update and return rewards record for a specific member."""
        summary = cls.calculate_engagement_score(member_id)
        score = summary['engagement_score']
        discount = cls.calculate_discount_band(score)

        settings = RewardSettings.get_settings()
        profit_pool = settings['profit_sharing_pool']

        conn = get_db()
        cursor = conn.cursor()

        # Calculate total club engagement score across all members for profit sharing allocation
        cursor.execute("SELECT id FROM members")
        all_member_ids = [row['id'] for row in cursor.fetchall()]

        total_club_score = 0.0
        member_scores = {}
        for m_id in all_member_ids:
            m_score = cls.calculate_engagement_score(m_id)['engagement_score']
            member_scores[m_id] = m_score
            total_club_score += m_score

        # Calculate proportional earned profit share
        earned_share = 0.0
        if total_club_score > 0:
            earned_share = round((score / total_club_score) * profit_pool, 2)

        # Check existing active reward or create a new one
        cursor.execute("SELECT * FROM rewards WHERE member_id = ? AND status = 'active' ORDER BY id DESC LIMIT 1", (member_id,))
        reward = cursor.fetchone()

        if reward:
            cursor.execute('''
                UPDATE rewards
                SET engagement_score = ?, discount_percentage = ?, earned_profit_share = ?
                WHERE id = ?
            ''', (score, discount, earned_share, reward['id']))
            redemption_code = reward['redemption_code']
        else:
            redemption_code = f"FS-RED-{uuid.uuid4().hex[:8].upper()}"
            cursor.execute('''
                INSERT INTO rewards (member_id, engagement_score, discount_percentage, earned_profit_share, redemption_code, status)
                VALUES (?, ?, ?, ?, ?, 'active')
            ''', (member_id, score, discount, earned_share, redemption_code))

        conn.commit()
        conn.close()

        return {
            'engagement_score': score,
            'discount_percentage': discount,
            'earned_profit_share': earned_share,
            'redemption_code': redemption_code,
            'details': summary
        }


class FacilityTracker:
    @staticmethod
    def check_in(member_id, facility_name):
        """Check in member to facility with current timestamp."""
        conn = get_db()
        cursor = conn.cursor()
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        cursor.execute('''
            INSERT INTO facility_checkins (member_id, facility_name, check_in_time, status)
            VALUES (?, ?, ?, 'active')
        ''', (member_id, facility_name, now_str))
        conn.commit()
        checkin_id = cursor.lastrowid
        conn.close()
        return checkin_id

    @staticmethod
    def check_out(checkin_id):
        """Check out member from facility and calculate usage duration."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM facility_checkins WHERE id = ?", (checkin_id,))
        record = cursor.fetchone()
        
        if not record or record['status'] == 'completed':
            conn.close()
            return None

        in_time = datetime.strptime(record['check_in_time'], "%Y-%m-%d %H:%M:%S")
        out_time = datetime.now()
        out_str = out_time.strftime("%Y-%m-%d %H:%M:%S")
        duration_mins = max(1, int((out_time - in_time).total_seconds() / 60))

        cursor.execute('''
            UPDATE facility_checkins
            SET check_out_time = ?, duration_minutes = ?, status = 'completed'
            WHERE id = ?
        ''', (out_str, duration_mins, checkin_id))

        # Log as a visit activity for engagement score calculation
        cursor.execute('''
            INSERT INTO activities (member_id, activity_type, service_name, transaction_value)
            VALUES (?, 'visit', ?, 0.0)
        ''', (record['member_id'], f"Facility Use: {record['facility_name']} ({duration_mins} mins)"))

        conn.commit()
        conn.close()
        return duration_mins


class GuestManager:
    @staticmethod
    def create_guest_id(host_member_id, guest_name):
        """Generate a guest ID for visitors without a member ID."""
        conn = get_db()
        cursor = conn.cursor()
        guest_code = f"GST-{uuid.uuid4().hex[:6].upper()}"
        cursor.execute('''
            INSERT INTO guest_ids (guest_code, guest_name, host_member_id)
            VALUES (?, ?, ?)
        ''', (guest_code, guest_name, host_member_id))
        
        # Log referral for host member
        cursor.execute('''
            INSERT INTO activities (member_id, activity_type, service_name, transaction_value, guest_count)
            VALUES (?, 'referral', ?, 0.0, 1)
        ''', (host_member_id, f"Guest Pass Generated for {guest_name} ({guest_code})"))

        conn.commit()
        guest_id = cursor.lastrowid
        conn.close()
        return {'id': guest_id, 'guest_code': guest_code, 'guest_name': guest_name}

    @staticmethod
    def record_guest_spending(guest_code, service_name, amount):
        """Record spending by a guest using their guest ID code."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM guest_ids WHERE guest_code = ?", (guest_code,))
        guest = cursor.fetchone()
        
        if not guest:
            conn.close()
            return False

        cursor.execute('''
            INSERT INTO guest_activities (guest_id, activity_type, service_name, transaction_value)
            VALUES (?, 'purchase', ?, ?)
        ''', (guest['id'], service_name, amount))

        conn.commit()
        conn.close()
        return True


class CSVReportGenerator:
    @staticmethod
    def export_member_usage_logs():
        """Export member activities and facility check-ins to CSV string."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute('''
            SELECT m.member_code, m.full_name, a.activity_type, a.service_name,
                   a.transaction_value, a.guest_count, a.created_at
            FROM activities a
            JOIN members m ON a.member_id = m.id
            ORDER BY a.created_at DESC
        ''')
        rows = cursor.fetchall()
        conn.close()

        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(['Member Code', 'Full Name', 'Activity Type', 'Service / Description', 'Transaction Value ($)', 'Guest Referrals', 'Timestamp'])
        
        for r in rows:
            writer.writerow([r['member_code'], r['full_name'], r['activity_type'], r['service_name'], f"{r['transaction_value']:.2f}", r['guest_count'], r['created_at']])

        return output.getvalue()

    @staticmethod
    def export_financial_reward_summaries():
        """Export financial rewards and profit sharing distribution summaries to CSV string."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT id FROM members")
        member_ids = [row['id'] for row in cursor.fetchall()]
        conn.close()

        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(['Member Code', 'Full Name', 'Membership Type', 'Engagement Score', 'Discount Band (%)', 'Earned Profit Share ($)', 'Redemption Code', 'Status'])

        conn = get_db()
        cursor = conn.cursor()
        for m_id in member_ids:
            rewards_info = EngagementEngine.update_member_rewards(m_id)
            cursor.execute('''
                SELECT m.member_code, m.full_name, m.membership_type
                FROM members m WHERE m.id = ?
            ''', (m_id,))
            m_info = cursor.fetchone()
            writer.writerow([
                m_info['member_code'],
                m_info['full_name'],
                m_info['membership_type'],
                f"{rewards_info['engagement_score']:.2f}",
                f"{rewards_info['discount_percentage']:.1f}%",
                f"${rewards_info['earned_profit_share']:.2f}",
                rewards_info['redemption_code'],
                'Active'
            ])
        conn.close()

        return output.getvalue()
