import uuid
import csv
import io
from datetime import datetime
from database import get_db

class RewardSettings:
    @staticmethod
    def get_settings():
        """Retrieve active algorithm weights and profit pool settings."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM reward_settings ORDER BY id DESC LIMIT 1")
        settings = cursor.fetchone()
        conn.close()
        return settings

    @staticmethod
    def update_settings(visit_weight, spending_weight, referral_weight, facility_weight,
                        loyalty_weight, profit_sharing_pool, premium_multiplier=1.15, vip_multiplier=1.30):
        """Update algorithm weights and profit pool settings."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO reward_settings (
                visit_weight, spending_weight, referral_weight, facility_weight,
                loyalty_weight, premium_multiplier, vip_multiplier, profit_sharing_pool
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ''', (visit_weight, spending_weight, referral_weight, facility_weight,
              loyalty_weight, premium_multiplier, vip_multiplier, profit_sharing_pool))
        conn.commit()
        conn.close()


class EngagementEngine:
    @staticmethod
    def calculate_engagement_score(member_id):
        """
        Calculate a member's total engagement score based on configurable factors.
        Uses ALL available club data sources:
        - Member direct visits (activities 'visit')
        - Member direct spending (activities 'purchase')
        - Guest referrals count (activities 'referral' guest_count)
        - Guest spending attached to member (guest_activities joined by host)
        - Facility usage minutes (facility_checkins duration, member + guest)
        - Membership loyalty (months since join_date)
        - Membership tier multiplier (Member / Premium / VIP)
        """
        settings = RewardSettings.get_settings()
        v_weight = settings['visit_weight']
        s_weight = settings['spending_weight']
        r_weight = settings['referral_weight']
        f_weight = settings['facility_weight']
        l_weight = settings['loyalty_weight']
        premium_mult = settings['premium_multiplier']
        vip_mult = settings['vip_multiplier']

        conn = get_db()
        cursor = conn.cursor()

        # Count total member visits
        cursor.execute("SELECT COUNT(*) FROM activities WHERE member_id = ? AND activity_type = 'visit'", (member_id,))
        visit_count = cursor.fetchone()[0]

        # Calculate member direct spending
        cursor.execute("SELECT COALESCE(SUM(transaction_value), 0.0) FROM activities WHERE member_id = ? AND activity_type = 'purchase'", (member_id,))
        direct_spending = cursor.fetchone()[0]

        # Calculate total guest referrals count
        cursor.execute("SELECT COALESCE(SUM(guest_count), 0) FROM activities WHERE member_id = ? AND activity_type = 'referral'", (member_id,))
        direct_referrals = cursor.fetchone()[0]

        # Calculate guest spending generated by this member's guests
        cursor.execute('''
            SELECT COALESCE(SUM(ga.transaction_value), 0.0)
            FROM guest_activities ga
            JOIN guest_ids g ON ga.guest_id = g.id
            WHERE g.host_member_id = ?
        ''', (member_id,))
        guest_spending = cursor.fetchone()[0]

        # Calculate facility usage minutes (completed member + guest sessions)
        cursor.execute('''
            SELECT COALESCE(SUM(duration_minutes), 0)
            FROM facility_checkins
            WHERE member_id = ? AND status = 'completed'
        ''', (member_id,))
        facility_minutes = cursor.fetchone()[0]

        # Calculate membership loyalty: months since the member joined
        cursor.execute("SELECT membership_type, join_date FROM members WHERE id = ?", (member_id,))
        member_row = cursor.fetchone()

        conn.close()

        # Normalize membership tier so 'premium', 'Premium ', 'VIP' all resolve
        membership_type = (member_row['membership_type'] or 'Member').strip().title() if member_row else 'Member'
        # Loyalty: full elapsed months, floored on days (e.g. 45 days = 1 month)
        loyalty_months = 0
        if member_row and member_row['join_date']:
            try:
                join_dt = datetime.strptime(member_row['join_date'][:10], "%Y-%m-%d")
                today = datetime.now()
                loyalty_months = max(0, (today - join_dt).days // 30)
            except ValueError:
                loyalty_months = 0

        total_spending = direct_spending + guest_spending

        # Score each data source independently
        visit_points = visit_count * v_weight
        spending_points = total_spending * s_weight
        referral_points = direct_referrals * r_weight
        facility_points = facility_minutes * f_weight
        loyalty_points = loyalty_months * l_weight

        base_score = visit_points + spending_points + referral_points + facility_points + loyalty_points

        # Membership tier multiplier (Premium / VIP get a boost on their base score)
        if membership_type == 'Vip':
            tier_multiplier = vip_mult
        elif membership_type == 'Premium':
            tier_multiplier = premium_mult
        else:
            tier_multiplier = 1.0

        score = base_score * tier_multiplier

        return {
            'visit_count': visit_count,
            'visit_points': round(visit_points, 2),
            'direct_spending': direct_spending,
            'guest_spending': guest_spending,
            'total_spending': total_spending,
            'spending_points': round(spending_points, 2),
            'guest_referrals': direct_referrals,
            'referral_points': round(referral_points, 2),
            'facility_minutes': facility_minutes,
            'facility_points': round(facility_points, 2),
            'loyalty_months': loyalty_months,
            'loyalty_points': round(loyalty_points, 2),
            'membership_type': membership_type,
            'tier_multiplier': tier_multiplier,
            'base_score': round(base_score, 2),
            'engagement_score': round(score, 2)
        }

    @staticmethod
    def calculate_discount_band(score):
        """Map engagement score to personalized discount percentage band.
        Thresholds are scaled to the full scoring model (visits, spending,
        referrals, facility minutes, loyalty, tier multiplier)."""
        if score >= 900:
            return 20.0
        elif score >= 500:
            return 15.0
        elif score >= 250:
            return 10.0
        elif score >= 100:
            return 5.0
        return 0.0

    @classmethod
    def update_member_rewards(cls, member_id):
        """Update and return rewards record for a specific member."""
        summary = cls.calculate_engagement_score(member_id)
        score = summary['engagement_score']
        discount = cls.calculate_discount_band(score)

        settings = RewardSettings.get_settings()
        profit_pool = settings['profit_sharing_pool']

        conn = get_db()
        cursor = conn.cursor()

        # Calculate total club engagement score across all members for profit sharing allocation
        cursor.execute("SELECT id FROM members")
        all_member_ids = [row['id'] for row in cursor.fetchall()]

        total_club_score = 0.0
        member_scores = {}
        for m_id in all_member_ids:
            m_score = cls.calculate_engagement_score(m_id)['engagement_score']
            member_scores[m_id] = m_score
            total_club_score += m_score

        # Calculate proportional earned profit share
        earned_share = 0.0
        if total_club_score > 0:
            earned_share = round((score / total_club_score) * profit_pool, 2)

        # Check existing active reward or create a new one
        cursor.execute("SELECT * FROM rewards WHERE member_id = ? AND status = 'active' ORDER BY id DESC LIMIT 1", (member_id,))
        reward = cursor.fetchone()

        if reward:
            cursor.execute('''
                UPDATE rewards
                SET engagement_score = ?, discount_percentage = ?, earned_profit_share = ?
                WHERE id = ?
            ''', (score, discount, earned_share, reward['id']))
            redemption_code = reward['redemption_code']
        else:
            redemption_code = f"FS-RED-{uuid.uuid4().hex[:8].upper()}"
            cursor.execute('''
                INSERT INTO rewards (member_id, engagement_score, discount_percentage, earned_profit_share, redemption_code, status)
                VALUES (?, ?, ?, ?, ?, 'active')
            ''', (member_id, score, discount, earned_share, redemption_code))

        conn.commit()
        conn.close()

        return {
            'engagement_score': score,
            'discount_percentage': discount,
            'earned_profit_share': earned_share,
            'redemption_code': redemption_code,
            'details': summary
        }


class FacilityTracker:
    @staticmethod
    def check_in(member_id, facility_name):
        """Check in member to facility with current timestamp."""
        conn = get_db()
        cursor = conn.cursor()
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        cursor.execute('''
            INSERT INTO facility_checkins (member_id, facility_name, check_in_time, status)
            VALUES (?, ?, ?, 'active')
        ''', (member_id, facility_name, now_str))
        conn.commit()
        checkin_id = cursor.lastrowid
        conn.close()
        return checkin_id

    @staticmethod
    def guest_check_in(guest_id, host_member_id, facility_name):
        """Check a guest into a facility, linked to their host member."""
        conn = get_db()
        cursor = conn.cursor()
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        cursor.execute('''
            INSERT INTO facility_checkins (member_id, guest_id, facility_name, check_in_time, status)
            VALUES (?, ?, ?, ?, 'active')
        ''', (host_member_id, guest_id, facility_name, now_str))
        conn.commit()
        checkin_id = cursor.lastrowid
        conn.close()
        return checkin_id

    @staticmethod
    def check_out(checkin_id):
        """Check out member from facility and calculate usage duration."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM facility_checkins WHERE id = ?", (checkin_id,))
        record = cursor.fetchone()
        
        if not record or record['status'] == 'completed':
            conn.close()
            return None

        in_time = datetime.strptime(record['check_in_time'], "%Y-%m-%d %H:%M:%S")
        out_time = datetime.now()
        out_str = out_time.strftime("%Y-%m-%d %H:%M:%S")
        duration_mins = max(1, int((out_time - in_time).total_seconds() / 60))

        cursor.execute('''
            UPDATE facility_checkins
            SET check_out_time = ?, duration_minutes = ?, status = 'completed'
            WHERE id = ?
        ''', (out_str, duration_mins, checkin_id))

        # Log as a visit activity for engagement score calculation
        # Guest sessions are recorded on the guest ledger instead of the member's activity log
        if record['guest_id']:
            cursor.execute('''
                INSERT INTO guest_activities (guest_id, activity_type, service_name, transaction_value)
                VALUES (?, 'facility', ?, 0.0)
            ''', (record['guest_id'], f"Facility Use: {record['facility_name']} ({duration_mins} mins)"))
        else:
            cursor.execute('''
                INSERT INTO activities (member_id, activity_type, service_name, transaction_value)
                VALUES (?, 'visit', ?, 0.0)
            ''', (record['member_id'], f"Facility Use: {record['facility_name']} ({duration_mins} mins)"))

        conn.commit()
        conn.close()
        return duration_mins


class GuestManager:
    @staticmethod
    def get_guest_by_code(guest_code):
        """Look up a guest pass by its code."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM guest_ids WHERE guest_code = ?", (guest_code,))
        guest = cursor.fetchone()
        conn.close()
        return guest

    @staticmethod
    def record_spending(guest_id, service_name, amount):
        """Record spending for a guest by guest id (credits their host member)."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO guest_activities (guest_id, activity_type, service_name, transaction_value)
            VALUES (?, 'purchase', ?, ?)
        ''', (guest_id, service_name, amount))
        conn.commit()
        conn.close()
        return True

    @staticmethod
    def create_guest_id(host_member_id, guest_name):
        """Generate a guest ID for visitors without a member ID."""
        conn = get_db()
        cursor = conn.cursor()
        guest_code = f"GST-{uuid.uuid4().hex[:6].upper()}"
        cursor.execute('''
            INSERT INTO guest_ids (guest_code, guest_name, host_member_id)
            VALUES (?, ?, ?)
        ''', (guest_code, guest_name, host_member_id))
        guest_id = cursor.lastrowid
        
        # Log referral for host member
        cursor.execute('''
            INSERT INTO activities (member_id, activity_type, service_name, transaction_value, guest_count)
            VALUES (?, 'referral', ?, 0.0, 1)
        ''', (host_member_id, f"Guest Pass Generated for {guest_name} ({guest_code})"))

        conn.commit()
        conn.close()
        return {'id': guest_id, 'guest_code': guest_code, 'guest_name': guest_name}

    @staticmethod
    def record_guest_spending(guest_code, service_name, amount):
        """Record spending by a guest using their guest ID code."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM guest_ids WHERE guest_code = ?", (guest_code,))
        guest = cursor.fetchone()
        
        if not guest:
            conn.close()
            return False

        cursor.execute('''
            INSERT INTO guest_activities (guest_id, activity_type, service_name, transaction_value)
            VALUES (?, 'purchase', ?, ?)
        ''', (guest['id'], service_name, amount))

        conn.commit()
        conn.close()
        return True


class ReceiptManager:
    """QR expense receipts: admins issue a receipt voucher with a unique
    RCPT-XXXX code; members scan the QR at the end of the receipt to log
    the expense automatically. Each receipt can be scanned exactly once
    (deduplicated) — a member scan logs it to their ledger, a guest scan
    logs it to the guest ledger and credits the host member."""

    @staticmethod
    def issue_receipt(service_name, amount):
        """Create a new unscanned expense receipt voucher."""
        conn = get_db()
        cursor = conn.cursor()
        receipt_code = f"RCPT-{uuid.uuid4().hex[:6].upper()}"
        cursor.execute('''
            INSERT INTO receipts (receipt_code, service_name, amount)
            VALUES (?, ?, ?)
        ''', (receipt_code, service_name, amount))
        conn.commit()
        receipt_id = cursor.lastrowid
        conn.close()
        return {'id': receipt_id, 'receipt_code': receipt_code, 'service_name': service_name, 'amount': amount}

    @staticmethod
    def get_receipt_by_code(receipt_code):
        """Look up a receipt by its RCPT-XXXX code."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM receipts WHERE receipt_code = ?", (receipt_code,))
        receipt = cursor.fetchone()
        conn.close()
        return receipt

    @staticmethod
    def redeem_for_member(receipt_code, member_id):
        """Scan a receipt QR for a member — logs the expense to their activity
        ledger. Returns dict with 'ok' and 'message'. A receipt that has
        already been scanned is rejected (deduplication)."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM receipts WHERE receipt_code = ?", (receipt_code,))
        receipt = cursor.fetchone()
        if not receipt:
            conn.close()
            return {'ok': False, 'message': f'Invalid receipt code "{receipt_code}". Please scan a valid receipt QR.'}
        if receipt['status'] == 'scanned':
            conn.close()
            return {'ok': False, 'message': f'Receipt {receipt_code} has already been scanned and logged.'}

        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        # Atomic deduplication: only one request can flip status unscanned->scanned.
        cursor.execute('''
            UPDATE receipts SET status = 'scanned', scanned_by_member = ?, scanned_at = ?
            WHERE id = ? AND status = 'unscanned'
        ''', (member_id, now_str, receipt['id']))
        if cursor.rowcount == 0:
            conn.close()
            return {'ok': False, 'message': f'Receipt {receipt_code} has already been scanned and logged.'}
        cursor.execute('''
            INSERT INTO activities (member_id, activity_type, service_name, transaction_value)
            VALUES (?, 'purchase', ?, ?)
        ''', (member_id, receipt['service_name'], receipt['amount']))
        conn.commit()
        conn.close()
        return {'ok': True, 'message': f'Expense of ${receipt["amount"]:.2f} for {receipt["service_name"]} logged from receipt {receipt_code}!'}

    @staticmethod
    def redeem_for_guest(receipt_code, guest_id):
        """Scan a receipt QR for a guest — logs the expense to the guest
        ledger (credited to their host member's rewards). Deduplicated."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM receipts WHERE receipt_code = ?", (receipt_code,))
        receipt = cursor.fetchone()
        if not receipt:
            conn.close()
            return {'ok': False, 'message': f'Invalid receipt code "{receipt_code}". Please scan a valid receipt QR.'}
        if receipt['status'] == 'scanned':
            conn.close()
            return {'ok': False, 'message': f'Receipt {receipt_code} has already been scanned and logged.'}

        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        # Atomic deduplication: only one request can flip status unscanned->scanned.
        cursor.execute('''
            UPDATE receipts SET status = 'scanned', scanned_by_guest = ?, scanned_at = ?
            WHERE id = ? AND status = 'unscanned'
        ''', (guest_id, now_str, receipt['id']))
        if cursor.rowcount == 0:
            conn.close()
            return {'ok': False, 'message': f'Receipt {receipt_code} has already been scanned and logged.'}
        cursor.execute('''
            INSERT INTO guest_activities (guest_id, activity_type, service_name, transaction_value)
            VALUES (?, 'purchase', ?, ?)
        ''', (guest_id, receipt['service_name'], receipt['amount']))
        conn.commit()
        conn.close()
        return {'ok': True, 'message': f'Purchase of ${receipt["amount"]:.2f} from receipt {receipt_code} — credited to your host member!'}


class CSVReportGenerator:
    @staticmethod
    def export_member_usage_logs():
        """Export member activities and facility check-ins to CSV string."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute('''
            SELECT m.member_code, m.full_name, a.activity_type, a.service_name,
                   a.transaction_value, a.guest_count, a.created_at
            FROM activities a
            JOIN members m ON a.member_id = m.id
            ORDER BY a.created_at DESC
        ''')
        rows = cursor.fetchall()
        conn.close()

        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(['Member Code', 'Full Name', 'Activity Type', 'Service / Description', 'Transaction Value ($)', 'Guest Referrals', 'Timestamp'])
        
        for r in rows:
            writer.writerow([r['member_code'], r['full_name'], r['activity_type'], r['service_name'], f"{r['transaction_value']:.2f}", r['guest_count'], r['created_at']])

        return output.getvalue()

    @staticmethod
    def export_financial_reward_summaries():
        """Export financial rewards and profit sharing distribution summaries to CSV string."""
        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT id FROM members")
        member_ids = [row['id'] for row in cursor.fetchall()]
        conn.close()

        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(['Member Code', 'Full Name', 'Membership Type', 'Engagement Score', 'Discount Band (%)', 'Earned Profit Share ($)', 'Redemption Code', 'Status'])

        conn = get_db()
        cursor = conn.cursor()
        for m_id in member_ids:
            rewards_info = EngagementEngine.update_member_rewards(m_id)
            cursor.execute('''
                SELECT m.member_code, m.full_name, m.membership_type
                FROM members m WHERE m.id = ?
            ''', (m_id,))
            m_info = cursor.fetchone()
            writer.writerow([
                m_info['member_code'],
                m_info['full_name'],
                m_info['membership_type'],
                f"{rewards_info['engagement_score']:.2f}",
                f"{rewards_info['discount_percentage']:.1f}%",
                f"${rewards_info['earned_profit_share']:.2f}",
                rewards_info['redemption_code'],
                'Active'
            ])
        conn.close()

        return output.getvalue()
